
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Role') THEN
        CREATE TYPE "Role" AS ENUM ('OWNER', 'ADMIN', 'MOD', 'SUPPORT', 'SYSTEM', 'USER');
    END IF;
END $$;

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW."updatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE IF NOT EXISTS "Mellow" (
    "id"               BIGINT PRIMARY KEY DEFAULT 1,
    "model"            TEXT DEFAULT 'gpt-3.5-turbo',
    "prompt"           TEXT DEFAULT 'You are Mellow',
    "temperature"      DOUBLE PRECISION NOT NULL DEFAULT 0.6,
    "presencePenalty"  DOUBLE PRECISION NOT NULL DEFAULT 0.6,
    "frequencyPenalty" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "maxTokens"        INTEGER NOT NULL DEFAULT 300,
    "enabled"          BOOLEAN NOT NULL DEFAULT true,
    "checkInTools"     BOOLEAN NOT NULL DEFAULT true,
    "copingTools"      BOOLEAN NOT NULL DEFAULT true,
    "ghostTools"       BOOLEAN NOT NULL DEFAULT true,
    "crisisTools"      BOOLEAN NOT NULL DEFAULT true,
    "owners"           TEXT[] NOT NULL DEFAULT '{}',
    "feedbackLogs"     BIGINT,
    "reportLogs"       BIGINT,
    "serverId"         BIGINT,
    "adminId"          BIGINT,
    "modId"            BIGINT,
    "logId"            BIGINT
);

INSERT INTO "Mellow" ("id", "model")
VALUES (1, 'claude-haiku-4-5')
ON CONFLICT ("id") DO NOTHING;

CREATE TABLE IF NOT EXISTS "User" (
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"    TEXT NOT NULL,
    "role"        "Role" NOT NULL DEFAULT 'USER',
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isBanned"    BOOLEAN NOT NULL DEFAULT false,
    "bannedUntil" TIMESTAMP(3),
    "banReason"   TEXT,
    "discordId"   TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "User_discordId_key" ON "User" ("discordId");
CREATE INDEX IF NOT EXISTS "User_role_idx" ON "User" ("role");
CREATE INDEX IF NOT EXISTS "User_isBanned_idx" ON "User" ("isBanned");
CREATE INDEX IF NOT EXISTS "User_createdAt_idx" ON "User" ("createdAt");

CREATE TABLE IF NOT EXISTS "Guild" (
    "id"                    BIGINT PRIMARY KEY,
    "name"                  TEXT NOT NULL,
    "ownerId"               BIGINT NOT NULL,
    "joinedAt"              TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isBanned"              BOOLEAN NOT NULL DEFAULT false,
    "bannedUntil"           TIMESTAMP(3),
    "banReason"             TEXT,
    "systemRoleId"          TEXT,
    "systemChannelId"       TEXT,
    "systemLogsEnabled"     BOOLEAN NOT NULL DEFAULT false,
    "auditLogChannelId"     TEXT,
    "modAlertChannelId"     TEXT,
    "modLogChannelId"       TEXT,
    "checkInChannelId"      TEXT,
    "copingToolLogId"       TEXT,
    "enableCheckIns"        BOOLEAN NOT NULL DEFAULT true,
    "enableGhostLetters"    BOOLEAN NOT NULL DEFAULT true,
    "enableCrisisAlerts"    BOOLEAN NOT NULL DEFAULT true,
    "moderatorRoleId"       TEXT,
    "autoModEnabled"        BOOLEAN NOT NULL DEFAULT false,
    "autoModLevel"          INTEGER,
    "language"              TEXT DEFAULT 'en',
    "disableContextLogging" BOOLEAN NOT NULL DEFAULT false,
    "discordId"             TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "Guild_discordId_key" ON "Guild" ("discordId");
CREATE INDEX IF NOT EXISTS "Guild_ownerId_idx" ON "Guild" ("ownerId");
CREATE INDEX IF NOT EXISTS "Guild_isBanned_idx" ON "Guild" ("isBanned");
CREATE INDEX IF NOT EXISTS "Guild_joinedAt_idx" ON "Guild" ("joinedAt");
CREATE INDEX IF NOT EXISTS "Guild_language_idx" ON "Guild" ("language");

CREATE TABLE IF NOT EXISTS "ConversationHistory" (
    "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"       BIGINT NOT NULL REFERENCES "User" ("id"),
    "content"      TEXT NOT NULL,
    "isAiResponse" BOOLEAN NOT NULL,
    "timestamp"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "channelId"    TEXT,
    "guildId"      TEXT,
    "messageId"    TEXT,
    "contextType"  TEXT NOT NULL DEFAULT 'conversation',
    "parentId"     INTEGER REFERENCES "ConversationHistory" ("id"),
    "metadata"     JSONB
);
CREATE INDEX IF NOT EXISTS "ConversationHistory_userId_timestamp_idx" ON "ConversationHistory" ("userId", "timestamp");
CREATE INDEX IF NOT EXISTS "ConversationHistory_channelId_timestamp_idx" ON "ConversationHistory" ("channelId", "timestamp");
CREATE INDEX IF NOT EXISTS "ConversationHistory_guildId_timestamp_idx" ON "ConversationHistory" ("guildId", "timestamp");
CREATE INDEX IF NOT EXISTS "ConversationHistory_contextType_timestamp_idx" ON "ConversationHistory" ("contextType", "timestamp");
CREATE INDEX IF NOT EXISTS "ConversationHistory_messageId_idx" ON "ConversationHistory" ("messageId");

CREATE TABLE IF NOT EXISTS "MoodCheckIn" (
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"      BIGINT NOT NULL REFERENCES "User" ("id"),
    "mood"        TEXT NOT NULL,
    "intensity"   INTEGER DEFAULT 3,
    "activity"    TEXT,
    "note"        TEXT,
    "nextCheckIn" TIMESTAMP(3),
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "MoodCheckIn_userId_createdAt_idx" ON "MoodCheckIn" ("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "MoodCheckIn_mood_idx" ON "MoodCheckIn" ("mood");
CREATE INDEX IF NOT EXISTS "MoodCheckIn_nextCheckIn_idx" ON "MoodCheckIn" ("nextCheckIn");

CREATE TABLE IF NOT EXISTS "GhostLetter" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"    BIGINT NOT NULL REFERENCES "User" ("id"),
    "content"   TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "GhostLetter_userId_createdAt_idx" ON "GhostLetter" ("userId", "createdAt");

CREATE TABLE IF NOT EXISTS "CopingToolUsage" (
    "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"   BIGINT NOT NULL REFERENCES "User" ("id"),
    "toolName" TEXT NOT NULL,
    "usedAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "CopingToolUsage_userId_usedAt_idx" ON "CopingToolUsage" ("userId", "usedAt");
CREATE INDEX IF NOT EXISTS "CopingToolUsage_toolName_usedAt_idx" ON "CopingToolUsage" ("toolName", "usedAt");

CREATE TABLE IF NOT EXISTS "CrisisEvent" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"     BIGINT NOT NULL REFERENCES "User" ("id"),
    "detectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "details"    TEXT,
    "escalated"  BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS "CrisisEvent_userId_detectedAt_idx" ON "CrisisEvent" ("userId", "detectedAt");
CREATE INDEX IF NOT EXISTS "CrisisEvent_escalated_detectedAt_idx" ON "CrisisEvent" ("escalated", "detectedAt");

CREATE TABLE IF NOT EXISTS "ModAction" (
    "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guildId"      BIGINT NOT NULL REFERENCES "Guild" ("id"),
    "moderatorId"  BIGINT NOT NULL REFERENCES "User" ("id"),
    "targetUserId" BIGINT NOT NULL,
    "action"       TEXT NOT NULL,
    "reason"       TEXT,
    "roleId"       BIGINT,
    "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "ModAction_guildId_createdAt_idx" ON "ModAction" ("guildId", "createdAt");
CREATE INDEX IF NOT EXISTS "ModAction_moderatorId_createdAt_idx" ON "ModAction" ("moderatorId", "createdAt");
CREATE INDEX IF NOT EXISTS "ModAction_targetUserId_createdAt_idx" ON "ModAction" ("targetUserId", "createdAt");
CREATE INDEX IF NOT EXISTS "ModAction_action_createdAt_idx" ON "ModAction" ("action", "createdAt");

CREATE TABLE IF NOT EXISTS "UserPreferences" (
    "id"                      BIGINT PRIMARY KEY REFERENCES "User" ("id"),
    "checkInInterval"         INTEGER NOT NULL DEFAULT 720,
    "lastReminder"            TIMESTAMP(3),
    "nextCheckIn"             TIMESTAMP(3),
    "remindersEnabled"        BOOLEAN NOT NULL DEFAULT true,
    "reminderMethod"          TEXT DEFAULT 'dm',
    "journalPrivacy"          BOOLEAN NOT NULL DEFAULT true,
    "aiPersonality"           TEXT DEFAULT 'gentle',
    "profileTheme"            TEXT DEFAULT 'blue',
    "language"                TEXT DEFAULT 'en',
    "timezone"                TEXT,
    "disableContextLogging"   BOOLEAN NOT NULL DEFAULT false,
    "disableCrisisDetection"  BOOLEAN NOT NULL DEFAULT false,
    "disableCrisisSupportDMs" BOOLEAN NOT NULL DEFAULT false,
    "createdAt"               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "UserPreferences_nextCheckIn_idx" ON "UserPreferences" ("nextCheckIn");
CREATE INDEX IF NOT EXISTS "UserPreferences_timezone_idx" ON "UserPreferences" ("timezone");
CREATE INDEX IF NOT EXISTS "UserPreferences_language_idx" ON "UserPreferences" ("language");
DROP TRIGGER IF EXISTS "UserPreferences_set_updated_at" ON "UserPreferences";
CREATE TRIGGER "UserPreferences_set_updated_at" BEFORE UPDATE ON "UserPreferences"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS "Feedback" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"    BIGINT REFERENCES "User" ("id"),
    "message"   TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "featured"  BOOLEAN NOT NULL DEFAULT false,
    "approved"  BOOLEAN NOT NULL DEFAULT false,
    "public"    BOOLEAN NOT NULL DEFAULT false
);
CREATE INDEX IF NOT EXISTS "Feedback_userId_createdAt_idx" ON "Feedback" ("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "Feedback_approved_public_idx" ON "Feedback" ("approved", "public");

CREATE TABLE IF NOT EXISTS "FeedbackReply" (
    "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "feedbackId" INTEGER NOT NULL REFERENCES "Feedback" ("id") ON DELETE CASCADE,
    "staffId"    BIGINT,
    "message"    TEXT NOT NULL,
    "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "FeedbackReply_feedbackId_createdAt_idx" ON "FeedbackReply" ("feedbackId", "createdAt");

CREATE TABLE IF NOT EXISTS "Report" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"    BIGINT REFERENCES "User" ("id"),
    "message"   TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status"    TEXT NOT NULL DEFAULT 'open'
);
CREATE INDEX IF NOT EXISTS "Report_userId_createdAt_idx" ON "Report" ("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "Report_status_createdAt_idx" ON "Report" ("status", "createdAt");

CREATE TABLE IF NOT EXISTS "ReportReply" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "reportId"  INTEGER NOT NULL REFERENCES "Report" ("id") ON DELETE CASCADE,
    "staffId"   BIGINT,
    "message"   TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "ReportReply_reportId_createdAt_idx" ON "ReportReply" ("reportId", "createdAt");

CREATE TABLE IF NOT EXISTS "JournalEntry" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"    BIGINT NOT NULL REFERENCES "User" ("id"),
    "content"   TEXT NOT NULL,
    "private"   BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "JournalEntry_userId_createdAt_idx" ON "JournalEntry" ("userId", "createdAt");
CREATE INDEX IF NOT EXISTS "JournalEntry_private_createdAt_idx" ON "JournalEntry" ("private", "createdAt");

CREATE TABLE IF NOT EXISTS "GratitudeEntry" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"    BIGINT NOT NULL REFERENCES "User" ("id"),
    "item"      TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "GratitudeEntry_userId_createdAt_idx" ON "GratitudeEntry" ("userId", "createdAt");

CREATE TABLE IF NOT EXISTS "CopingPlan" (
    "id"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId"    BIGINT NOT NULL REFERENCES "User" ("id"),
    "plan"      TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "CopingPlan_userId_updatedAt_idx" ON "CopingPlan" ("userId", "updatedAt");
DROP TRIGGER IF EXISTS "CopingPlan_set_updated_at" ON "CopingPlan";
CREATE TRIGGER "CopingPlan_set_updated_at" BEFORE UPDATE ON "CopingPlan"
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS "FavoriteCopingTool" (
    "id"     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES "User" ("id"),
    "tool"   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS "FavoriteCopingTool_userId_idx" ON "FavoriteCopingTool" ("userId");
CREATE INDEX IF NOT EXISTS "FavoriteCopingTool_tool_idx" ON "FavoriteCopingTool" ("tool");

CREATE TABLE IF NOT EXISTS "SystemLog" (
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guildId"     BIGINT REFERENCES "Guild" ("id"),
    "userId"      BIGINT REFERENCES "User" ("id"),
    "logType"     TEXT NOT NULL,
    "title"       TEXT NOT NULL,
    "description" TEXT,
    "metadata"    TEXT,
    "severity"    TEXT NOT NULL DEFAULT 'info',
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS "SystemLog_guildId_logType_createdAt_idx" ON "SystemLog" ("guildId", "logType", "createdAt");
CREATE INDEX IF NOT EXISTS "SystemLog_userId_logType_createdAt_idx" ON "SystemLog" ("userId", "logType", "createdAt");
CREATE INDEX IF NOT EXISTS "SystemLog_logType_createdAt_idx" ON "SystemLog" ("logType", "createdAt");
CREATE INDEX IF NOT EXISTS "SystemLog_severity_createdAt_idx" ON "SystemLog" ("severity", "createdAt");
