
DROP TABLE IF EXISTS "SystemLog" CASCADE;
DROP TABLE IF EXISTS "FavoriteCopingTool" CASCADE;
DROP TABLE IF EXISTS "CopingPlan" CASCADE;
DROP TABLE IF EXISTS "GratitudeEntry" CASCADE;
DROP TABLE IF EXISTS "JournalEntry" CASCADE;
DROP TABLE IF EXISTS "ReportReply" CASCADE;
DROP TABLE IF EXISTS "Report" CASCADE;
DROP TABLE IF EXISTS "FeedbackReply" CASCADE;
DROP TABLE IF EXISTS "Feedback" CASCADE;
DROP TABLE IF EXISTS "UserPreferences" CASCADE;
DROP TABLE IF EXISTS "ModAction" CASCADE;
DROP TABLE IF EXISTS "CrisisEvent" CASCADE;
DROP TABLE IF EXISTS "CopingToolUsage" CASCADE;
DROP TABLE IF EXISTS "GhostLetter" CASCADE;
DROP TABLE IF EXISTS "MoodCheckIn" CASCADE;
DROP TABLE IF EXISTS "ConversationHistory" CASCADE;
DROP TABLE IF EXISTS "Guild" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Mellow" CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();
DROP TYPE IF EXISTS "Role";
